version: 2.1

orbs:
  codacy_plugins_test: codacy/plugins-test@0.7.1

jobs:
  unit_test:
    docker:  # run the steps with Docker
      - image: crystallang/crystal:0.31.1
    working_directory: ~/codacy-ameba
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: shards install
      - run:
          name: Run test
          command: crystal spec

  publish_local:
    machine: true
    working_directory: ~/workdir
    steps:
      - checkout
      - run: 
          name: Publish tool docker locally
          command: docker build . -t $CIRCLE_PROJECT_REPONAME:latest
      - run:
          name: Save docker to file
          command: |
            docker save --output docker-image.tar $CIRCLE_PROJECT_REPONAME:latest
      - persist_to_workspace:
          root: ~/workdir
          paths:
            - '*'

  publish:
    machine: true
    working_directory: ~/workdir
    steps:
      - attach_workspace:
          at: ~/workdir
      - run:
          name: Load docker from file
          command: docker load --input docker-image.tar
      - deploy:
          name: Push application Docker image
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker tag $CIRCLE_PROJECT_REPONAME codacy/$CIRCLE_PROJECT_REPONAME
            docker tag $CIRCLE_PROJECT_REPONAME codacy/$CIRCLE_PROJECT_REPONAME:2.0.$CIRCLE_BUILD_NUM
            docker push codacy/$CIRCLE_PROJECT_REPONAME

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - unit_test
      - publish_local
      - codacy_plugins_test/run:
          name: plugins_test
          run_multiple_tests: true
          requires:
            - publish_local
      - publish:
          filters:
            branches:
              only: master
          requires:
            - unit_test
            - publish_local
            - plugins_test
