version: 2.1

orbs:
  codacy: codacy/base@2.0.1
  codacy_plugins_test: codacy/plugins-test@0.7.1

jobs:
  unit_test:
    docker: # run the steps with Docker
      - image: crystallang/crystal:0.31.1
    working_directory: ~/workdir
    steps:
      - attach_workspace:
          at: ~/workdir
      - run:
          name: Install dependencies
          command: shards install
      - run:
          name: Run test
          command: crystal spec

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - codacy/checkout_and_version
      - unit_test:
          requires:
            - codacy/checkout_and_version
      - codacy/shell:
          name: publish_local
          cmd: |
            docker build -t $CIRCLE_PROJECT_REPONAME:latest .
            docker save --output docker-image.tar $CIRCLE_PROJECT_REPONAME:latest
          persist_to_workspace: true
          requires:
            - codacy/checkout_and_version
      - codacy_plugins_test/run:
          name: plugins_test
          run_multiple_tests: true
          requires:
            - publish_local
      - codacy/shell:
          name: publish_dockerhub
          cmd: |
            docker load --input docker-image.tar
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker tag $CIRCLE_PROJECT_REPONAME codacy/$CIRCLE_PROJECT_REPONAME:latest
            docker tag $CIRCLE_PROJECT_REPONAME codacy/$CIRCLE_PROJECT_REPONAME:$(cat .version)
            docker push codacy/$CIRCLE_PROJECT_REPONAME
          filters:
            branches:
              only: master
          requires:
            - unit_test
            - publish_local
            - plugins_test
      - codacy/tag_version:
          requires:
            - publish_dockerhub
